language: python
python:
- '3.5'
- '3.6'
env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: BTgDEdGdKcg/KM1W1VYBRWwyEpneBUOC3BSZFnqBPZJ9nJoYuf16cdajBmt2Up2Dkq4tsucTyNaVCdaNaVTgKaIiTBM49LDh2efo8iPsAT1qLDEJ8T3irHeg46MpZNViMck532douURRgwY5ltkxBcOeTNdl/w0M2Gs1Gt/PYxeAti4hexZXlLlbTul11w0otYcIpvpDftgP4tG6KuxSSUOUb2e02R9CumBIJMI0pb9DzylBuAgkVST63CL7WfMOZNf3s5PqswFG17Nur62W3qCdz9iPmOk0T6QSTUeD6ATC4tQdytZtfqiktmoBBMC0ITGNvV63rDKDYkoMLH9AvE8uWFARZX0wqTT+bEWBYcaPMv2HNDpCmAczk3+VdnuUtviV1JVfJEk00f1zW+go323QIw/+8V1XsRuOvqG5tGUN97aogDZmBt4Kyu/xknwynUR7uMOM++vf1/+GVy6Nqzy0bhK3y6/TDzipCR0cFasW5TawnSJKbLI/vK7bMEUHqVQBUcTKNXdEJFHnKslaujvKhCSUdwykcV3u0xBiPNjq+elPWrk54rGQBro1S5MicjP45ZyHHIg1itU0ghiZyfZqUlb2pAgbiDoP1zlc++BYA8dBVKl/Gz6SzcSkKrfBkr5iZyLRPYS4XOuUGg/6WxXF9LUd7lpVZMkBEiaopZo=
  - secure: m3OV4ONzKaFrqJBPedUqUu2ZLstejOLs0a3pChrRe5rD4hto2VAsNeAYVh5ECy2Cg7T2AYqwRs5d/ohaRNUgIkO/TNRlXiOgvaZ4lx6RYaAjabdS1yzokyqasS8bCmHUpKJ3Ru5Y9gwARuYIVOaeaNk2RV1JH/0gWxac1UtU4E/VTlCxIlNR+XslkaOAHo63XyM5RohO+96Y1+5jgGsgWvmSZkXJByWnxuO1mk5Ql2VkwS0RO0Eznot2sflstL0S5ZJlDugyd8Y13QVBnvouIgXZdJShz6vMc8b3ShserhZ0dLzsBfgdEqRuEtRUNxE4q/lcw4aJvhcupAK7UysVDL9ewN8HiJPk6xuO0wqntaJtFQOLZNd9VxEzon5HioTVn18iitm38z7+NUv6NwvuGVTgQ/Cpw1Qp2cgl3933aCWKEJgkLYFCGjtRygvJSEODusfHsOc2z+nV1bVucNFBXOWD1fkucqRWTwq1JV703YdzMT3DqtpFASnhzTM2TyDwmdA1IZQj7wZ9YV6TXcapVOscfLhxcew9mQmiLzS+fEc3ORQJLAGFEA9BCygGt0abz1nYPYX4JPkQBQOgC8zpirEqSuuuA3xpbHzbRv+FI7ATdZKM3o9rR5mjBvZ4EwNm/W0wZLAZqmY7lwsbRa+kmTyfLPIA6Vil4BRsEiwg5Ps=
install:
- pip install pipenv
- pipenv install --dev --three
before_script:
- cp .env.example .env
script:
- pipenv run flake8 .
- pipenv run python manage.py test -v 2
